# Generated by Django 4.1.2 on 2022-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('arr_dep', models.CharField(blank=True, max_length=1, null=True)),
                ('terminal', models.CharField(blank=True, max_length=1, null=True)),
                ('code_ak', models.CharField(blank=True, max_length=5, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=10, null=True)),
                ('planned_time', models.TimeField(blank=True, null=True)),
                ('code_ap', models.CharField(blank=True, max_length=5, null=True)),
                ('airport', models.CharField(blank=True, max_length=20, null=True)),
                ('plane_type', models.CharField(blank=True, max_length=5, null=True)),
                ('parking_place_number', models.CharField(blank=True, max_length=4, null=True)),
                ('gate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('passengers_amount', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
