# Generated by Django 4.1.2 on 2022-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_points_roads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='location_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
