# Generated by Django 4.1.2 on 2022-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_points_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('trip_without_refueling', models.IntegerField(blank=True, null=True)),
                ('auto_task', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField(blank=True, null=True)),
                ('point_from', models.IntegerField(blank=True, null=True)),
                ('point_to', models.IntegerField(blank=True, null=True)),
                ('time_from', models.DateTimeField(blank=True, null=True)),
                ('time_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='working_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_period', models.DateTimeField(blank=True, null=True)),
                ('to_period', models.DateTimeField(blank=True, null=True)),
                ('bus_driver_id', models.IntegerField(blank=True, null=True)),
                ('bus_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
